### ISSUE TITLE
ModularUI 2.0.9 is not compatible with mother-ship mod

### ISSUE THREAD

**Issue by AykaSova** [bioastroiner/gt6scan#5]
Tha's the issue — gt6scanner 1.6.0 sit requires ModularUI only 2.0.8
Wath is a purpose for ModularUI 2.0.9 &

**Comment by bioastroiner** [comment]
Oh i see finally some other mod also depends on modularUI2 as well!

Tnx for the report i'll make a hotfix

**Comment by bioastroiner** [comment]
fixed in v1.7.0
https://github.com/bioastroiner/gt6scan/releases/latest
